Issue 263: Speech recognition cues
memphis-iis/mofacts-ies pull request #277
Opened 2021-09-14 18:59 UTC by JRustyHaner

Implements speech recognition cues as described in #263

2021-09-14 20:38 UTC, JRustyHaner commented
- Change icon to white when listening
- Change language when doing a button based question
- make sure each session type has a prompt

2021-09-14 20:39 UTC, andrewtackett requested changes
need to change color of mic on not transcribing, have diff text for button trial, make sure appears in both learningsession and assessmentsession

2021-09-15 13:14 UTC, JRustyHaner commented
@andrewtackett changed according to yesterday's discussion about the icon, message phrasing, and going to an on state for microphone icon during silence detected.

2021-09-15 15:06 UTC, JRustyHaner commented
@andrewtackett  fixed spacing and the issue discussed where icon was being displayed when voice prompts weren't required.

2021-09-15 17:56 UTC, JRustyHaner commented
@andrewtackett I compared the changes to the original and it should match up

2021-09-15 18:04 UTC, andrewtackett requested changes

2021-09-15 18:04 UTC, andrewtackett commented on mofacts/client/views/experiment/card.js
> -  } else if (typeof simCorrect === 'boolean') {
These lines are still deleted

2021-09-15 18:04 UTC, andrewtackett commented on mofacts/client/views/experiment/card.js
> +      //look at this for transcription prompt!
Remove this comment

2021-09-15 18:04 UTC, andrewtackett commented on mofacts/client/views/experiment/card.js
> +      //Change graphic and message
Remove this comment

2021-09-15 18:04 UTC, andrewtackett commented on mofacts/client/views/experiment/card.js
> +
Don't delete this

2021-09-15 18:04 UTC, andrewtackett commented on mofacts/client/views/experiment/card.js
> +    resetMainCardTimeout();
Don't add this here

2021-09-15 18:16 UTC, JRustyHaner commented
@andrewtackett  took me a minute, but its showing no subtractions on my end now.

2021-09-15 18:17 UTC, andrewtackett approved these changes
Looks good

2021-09-15 18:18 UTC, merged