Issue 279: Make it so audio input obeys pausedLocks session variable
memphis-iis/mofacts-ies pull request #280
Opened 2021-09-15 19:19 UTC by JRustyHaner

Fixes issue #279 by adding a pausedLocks check to voice_stop

2021-09-15 19:23 UTC, andrewtackett requested changes

2021-09-15 19:23 UTC, andrewtackett commented on mofacts/client/views/experiment/card.js
> +      } else if (!Session.get('recording') || Session.get('pausedLocks') != 0) {
Minor quibble but can you make the condition > 0 instead of != 0?  != 0 could be true if undefined or we accidentally subtract below 0.

2021-09-15 19:23 UTC, andrewtackett commented on mofacts/client/views/experiment/card.js
> +        console.log('pauseLocks remaining: ' + Session.get('pausedLocks'));
Delete this comment

2021-09-15 19:25 UTC, JRustyHaner commented
@andrewtackett removed and changed

2021-09-16 16:08 UTC, andrewtackett approved these changes
Looks good

2021-09-16 16:08 UTC, merged