Issue 269: Sentence incomplete
memphis-iis/mofacts-ies pull request #286
Opened 2021-09-17 16:06 UTC by JRustyHaner

-Reproduced bug by adding text and a second blank to testStim.json and dropping the database in postgres and re-initializing. This concatenated clozeText and text on the first run of a given card. Unsure if related.

Fix: reordering the condition statement on line 1225 in card.js

2021-09-17 16:13 UTC, JRustyHaner commented
@andrewtackett this fixed the issue with two blanks, but not three.

2021-09-17 16:33 UTC, JRustyHaner commented
![image](https://user-images.githubusercontent.com/46696077/133822979-1dc1ffb2-28d0-4db4-8adb-7b8359841090.png)

- Reproduced exact issue

2021-09-17 16:37 UTC, JRustyHaner commented
Behavior different error during practice:
![image](https://user-images.githubusercontent.com/46696077/133823501-e72e04df-d817-4b3a-b19d-7d9e6529886e.png)

Reproduced during test:
![image](https://user-images.githubusercontent.com/46696077/133823215-11690de1-a0a0-412c-8ca6-1d95634eb9b5.png)

2021-09-17 18:22 UTC, JRustyHaner commented
Text and ClozeText are put into the save display variable, having them both displayed in the html causes this issue. Tested 10/17 1:22PM

2021-09-21 17:08 UTC, andrewtackett reviewed
It would seem your solution doesn't do underlining for the second time the cloze answer is presented in the question. Also there's a random import in there at the top of unitEngine for some reason.

2021-09-21 17:36 UTC, JRustyHaner commented
@andrewtackett

2021-09-21 17:39 UTC, andrewtackett requested changes
This still doesn't address underlining the second instance of the cloze word.  Also please remove the reordering of assigning to currentQuestion, clozeText is preferred first for a reason.

2021-09-22 13:22 UTC, JRustyHaner commented
![image](https://user-images.githubusercontent.com/46696077/134351452-638c4b5d-fba5-4eaf-8bcd-86a3a53cdea0.png)

2021-09-22 13:22 UTC, JRustyHaner commented
@andrewtackett

2021-09-22 14:22 UTC, andrewtackett requested changes
Looks like injecting the <u></u> worked then?  Just strip out your testing stuff and I think this should be good.

2021-09-22 14:22 UTC, andrewtackett commented on mofacts/client/views/experiment/unitEngine.js
> +      // clozeQuestionParts.splice(1, 1);
Shouldn't have commented out code in final versions

2021-09-22 14:22 UTC, andrewtackett commented on mofacts/client/views/experiment/unitEngine.js
> +        console.log('clozeQuestionParts',i,clozeQuestionParts[i]);
Also should strip testing print statements

2021-09-22 14:22 UTC, andrewtackett commented on mofacts/client/views/experiment/unitEngine.js
> +          clozeQuestionParts[i] = '<u>' + clozeAnswerNoUnderscores + '&nbsp;&nbsp;&nbsp;&nbsp;' + '</u>';
Why 4 spaces here?

2021-09-22 14:36 UTC, JRustyHaner commented
@andrewtackett  removed console log and deprecated code

2021-09-22 15:02 UTC, merged