Issue265: Progress Monitors
memphis-iis/mofacts-ies pull request #291
Opened 2021-09-23 15:34 UTC by JRustyHaner

#265

2021-09-23 21:21 UTC, andrewtackett requested changes
A few minor changes.  Looks pretty good overall

2021-09-23 21:21 UTC, andrewtackett commented on mofacts/client/views/experimentReporting/studentReporting.js
> +import { Session } from 'meteor/session';
Is this necessary? I believe this is a meteor framework global, but I may have imported it to get rid of linting errors in other files

2021-09-23 21:21 UTC, andrewtackett commented on mofacts/client/views/experimentReporting/studentReporting.js
> +  } else {scorer.afterFlush(async function() {
Was this autocorrected from something like Timer?

2021-09-23 21:21 UTC, andrewtackett commented on mofacts/client/views/experimentReporting/studentReporting.js
> +    $(`#tdf-select option[value="${INVALID}"]`).prop('disabled', true);
Are those smart/back ticks?  Can this be done with single quotes instead?

2021-09-23 21:21 UTC, andrewtackett commented on mofacts/server/methods.js
> +async function getStimCountByTdfId(tdfId) {
This duplicates an existing function :P

2021-09-24 13:23 UTC, JRustyHaner commented
@andrewtackett

2021-09-24 14:01 UTC, andrewtackett approved these changes

2021-09-24 14:01 UTC, merged