Issue 253: Added question functionality to instructions
memphis-iis/mofacts-ies pull request #299
Opened 2021-09-27 20:35 UTC by JRustyHaner

#253 
using TDFs, a yes/no question can be displayed during /instructions interstitial. The results will be stored in the Session variable instructionQuestionResults, which can be passed into the p value calculations.

2021-09-27 21:17 UTC, andrewtackett requested changes
Did you update the documentation?

Also, I don't see any integration of the result back into the p parameters

2021-09-27 21:17 UTC, andrewtackett commented on mofacts/client/views/experiment/instructions.js
> +    question = Session.get('currentTdfFile').tdfs.tutor.unit[0].unitinstructionsquestion;
Doubt this should be hardcoded

2021-09-27 21:58 UTC, imrryr commented
I agree it shouldn't be hard coded

On Mon, Sep 27, 2021, 4:17 PM Andrew Tackett ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Did you update the documentation?
>
> Also, I don't see any integration of the result back into the p parameters
> ------------------------------
>
> In mofacts/client/views/experiment/instructions.js
> <https://github.com/memphis-iis/mofacts-ies/pull/299#discussion_r717051822>
> :
>
> > @@ -295,11 +295,23 @@ Template.instructions.helpers({
>
>      return img;
>    },
> -
> -  instructions: function() {
> -    return _.chain(Session.get('currentTdfUnit')).prop('unitinstructions').trim().value();
> +  instructionText: function(){
> +    text = Session.get('currentTdfFile').tdfs.tutor.unit[0].unitinstructions;
> +    return text;
> +  },
> +  instructionQuestion: function(){
> +    question = Session.get('currentTdfFile').tdfs.tutor.unit[0].unitinstructionsquestion;
>
> Doubt this should be hardcoded
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/memphis-iis/mofacts-ies/pull/299#pullrequestreview-764760338>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADDLPK2IKJ7TYLJU2HVKIV3UEDNPPANCNFSM5E3NDRVA>
> .
>

2021-09-27 22:01 UTC, imrryr commented
I'll try to think of a better alternative that fits future goals.

On Mon, Sep 27, 2021, 4:58 PM Philip Pavlik ***@***.***> wrote:

> I agree it shouldn't be hard coded
>
> On Mon, Sep 27, 2021, 4:17 PM Andrew Tackett ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> Did you update the documentation?
>>
>> Also, I don't see any integration of the result back into the p parameters
>> ------------------------------
>>
>> In mofacts/client/views/experiment/instructions.js
>> <https://github.com/memphis-iis/mofacts-ies/pull/299#discussion_r717051822>
>> :
>>
>> > @@ -295,11 +295,23 @@ Template.instructions.helpers({
>>
>>      return img;
>>    },
>> -
>> -  instructions: function() {
>> -    return _.chain(Session.get('currentTdfUnit')).prop('unitinstructions').trim().value();
>> +  instructionText: function(){
>> +    text = Session.get('currentTdfFile').tdfs.tutor.unit[0].unitinstructions;
>> +    return text;
>> +  },
>> +  instructionQuestion: function(){
>> +    question = Session.get('currentTdfFile').tdfs.tutor.unit[0].unitinstructionsquestion;
>>
>> Doubt this should be hardcoded
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/memphis-iis/mofacts-ies/pull/299#pullrequestreview-764760338>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/ADDLPK2IKJ7TYLJU2HVKIV3UEDNPPANCNFSM5E3NDRVA>
>> .
>>
>

2021-09-28 15:12 UTC, JRustyHaner commented
I removed the hard coding, it was throwing me for a loop because each unit has the possibility of throwing instructions, although card.js misses the first <unit> tag. Is that intentional? It could just check for if the unit[0] has unitinstructions defined. As a point to clarify, how should the question affect the p value, or should it be just stored?

2021-09-28 17:46 UTC, imrryr commented
So that definitely fulfills what we need however this ability to transfer
information from one unit to another is very powerful and we should
consider a future generalization of the ability. It sounds like it would
make sense to make that a different issue though unless what you have
created generalizes very easy...

On Tue, Sep 28, 2021, 12:15 PM JRustyHaner ***@***.***> wrote:

> @imrryr <https://github.com/imrryr> the current functionality that I put
> in sets the p.instructionQuestionResult to true or false for every card
> within the unit the user was on. The instructional question is not
> displayed again unless user data is cleared.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/memphis-iis/mofacts-ies/pull/299#issuecomment-929424816>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADDLPKZEWFUISDMJG5R5KGLUEHZZJANCNFSM5E3NDRVA>
> .
>

2021-09-28 17:51 UTC, JRustyHaner commented
ideally, if I were to generalize it further, I would allow for an array of questions ("On a scale of 1 to 5, how difficult is this material to understand?")to be asked with a variety of response types, ie, yes/no, multi choice, etc. Since these questions do not count against the scoring, it could be used to gather other data that the model could use as predictions. Sort of like a pre-exam questionaire.

2021-09-28 17:53 UTC, imrryr commented
Yes that's exactly the way it will be used after the grant in future work.
Clearly there's no big hurry on that then but it might be nice to discuss
tomorrow

On Tue, Sep 28, 2021, 12:51 PM JRustyHaner ***@***.***> wrote:

> ideally, if I were to generalize it further, I would allow for an array of
> questions ("On a scale of 1 to 5, how difficult is this material to
> understand?")to be asked with a variety of response types, ie, yes/no,
> multi choice, etc. Since these questions do not count against the scoring,
> it could be used to gather other data that the model could use as
> predictions. Sort of like a pre-exam questionaire.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/memphis-iis/mofacts-ies/pull/299#issuecomment-929488489>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADDLPK257PLDU7RM7TLXRQDUEH6BDANCNFSM5E3NDRVA>
> .
>

2021-10-08 15:53 UTC, JRustyHaner commented
@andrewtackett

2021-10-08 18:21 UTC, andrewtackett commented on mofacts/client/views/experiment/instructions.js
> +
extra whitespace

2021-10-08 18:21 UTC, andrewtackett commented on mofacts/client/views/experiment/instructions.js
> +
extra whitespace

2021-10-08 18:22 UTC, andrewtackett commented on mofacts/client/views/experiment/unitEngine.js
> +          instructionQuestionResult: session.get('instructionQuestionResult'),
Does this work with lowercase session?

2021-10-08 19:06 UTC, merged