Check for answer repetition
memphis-iis/mofacts-ies pull request #798
Opened 2022-05-16 18:51 UTC by JRustyHaner

fixes #35

2022-05-17 16:09 UTC, MegaGeese requested changes
This will work well if the user types the exact right answer; however, we want to allow for simple misspellings.

2022-05-17 20:20 UTC, MegaGeese requested changes

2022-05-17 20:20 UTC, MegaGeese commented on mofacts/client/views/experiment/answerAssess.js
> +      let userSecondAnswer = user.AnswerWords.slice(answerWordsCount, answerWordsCount);
`user.AnswerWords` would probably throw an error

2022-05-18 19:23 UTC, JRustyHaner commented
@MegaGeese derp

2022-05-20 19:23 UTC, merged